// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk5cvzUDudJW5BoWJIREeqpaUtviDLc_s',
    appId: '1:479591812530:web:5359f16bac1c282c14a8ab',
    messagingSenderId: '479591812530',
    projectId: 'chatter-64601',
    authDomain: 'chatter-64601.firebaseapp.com',
    storageBucket: 'chatter-64601.appspot.com',
    measurementId: 'G-JTHGV48HTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn_n03GYreWFNahNNrVX1UgDg7E6rJaPw',
    appId: '1:479591812530:android:f9410a2bcaa4009014a8ab',
    messagingSenderId: '479591812530',
    projectId: 'chatter-64601',
    storageBucket: 'chatter-64601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrCF4WddofQ5-yUkUV19fiKdfztMJO7b0',
    appId: '1:479591812530:ios:fe74eb66cc6cd5f114a8ab',
    messagingSenderId: '479591812530',
    projectId: 'chatter-64601',
    storageBucket: 'chatter-64601.appspot.com',
    iosClientId: '479591812530-3rcjdud4jj3g73p5cu386tlsnsrqdheo.apps.googleusercontent.com',
    iosBundleId: 'com.codehq.chatter',
  );
}
